apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: v1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: core
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
    csi:
      resizerReplicaCount: 1
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "config.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "config.${SECRET_DOMAIN}"
          secretName: "config-tls"