apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      chart: cert
      version: v1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: core
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3