apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: core
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.24.0
      pullPolicy: IfNotPresent

    env:
      DOMAIN: "https://bitwarden.${SECRET_DOMAIN}"
      INVITATIONS_ALLOWED: "true"
      SIGNUPS_ALLOWED: "false"
      SIGNUPS_DOMAINS_WHITELIST: "windsorfamily.org"
      WEBSOCKET_ENABLED: "true"
      YUBICO_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: YUBICO_CLIENT_ID
      YUBICO_SECRET_KEY:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: YUBICO_SECRET_KEY
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: ADMIN_TOKEN

    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hajimari.io/enable: "true"
          hajimari.io/icon: "lock"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "bitwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "bitwarden.${SECRET_DOMAIN}"
            secretName: "vaultwarden-tls"