apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: core
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.25.2
      pullPolicy: IfNotPresent

    env:
      DOMAIN: "https://bitwarden.${SECRET_DOMAIN}"
      INVITATIONS_ALLOWED: "true"
      SIGNUPS_ALLOWED: "false"
      SIGNUPS_DOMAINS_WHITELIST: "windsorfamily.org"
      WEBSOCKET_ENABLED: "true"
      YUBICO_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: YUBICO_CLIENT_ID
      YUBICO_SECRET_KEY:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: YUBICO_SECRET_KEY
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: ADMIN_TOKEN
      SMTP_FROM_NAME: Vault
      SMTP_FROM: noreply@windsorfamily.org
      SMTP_HOST: protonmail-bridge.apps.svc.cluster.local
      SMTP_USERNAME:
        valueFrom:
          secretKeyRef:
            name: protonmail-bridge-secrets
            key: BRIDGE_USERNAME
      SMTP_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: protonmail-bridge-secrets
            key: BRIDGE_PASSWORD
      SMTP_PORT: 25
      SMTP_SSL: "false"

    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/target: "windsorfamily.mynetgear.com"
        hosts:
          - host: "bitwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "bitwarden.${SECRET_DOMAIN}"
            secretName: "vaultwarden-tls"
