apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.14.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: core
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: nextcloud-secrets
      valuesKey: NEXTCLOUD_MARIADB_PASSWORD
      targetPath: mariadb.auth.password
      optional: false
    - kind: Secret
      name: nextcloud-secrets
      valuesKey: NEXTCLOUD_MARIADB_ROOT_PASSWORD
      targetPath: mariadb.auth.rootPassword
      optional: false
  values:
    image:
      repository: nextcloud
      tag: "24.0.1"

    replicaCount: 1

    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 500Gi

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: apps-nextcloud-dav-redirect@kubernetescrd,apps-nextcloud-hsts-header@kubernetescrd
        external-dns.alpha.kubernetes.io/target: "windsorfamily.mynetgear.com"
      hosts:
        - host: "cloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "cloud.${SECRET_DOMAIN}"
          secretName: "nextcloud-tls"

    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: NEXTCLOUD_ADMIN_USER
        passwordKey: NEXTCLOUD_ADMIN_PASSWORD
        smtpUsernameKey: PROTONMAIL_BRIDGE_USER
        smtpPasswordKey: PROTONMAIL_BRIDGE_PASSWORD
      mail:
        enabled: true
        fromAddress: noreply
        domain: windsorfamily.org
        smtp:
          host: protonmail-bridge.apps.svc.cluster.local
          secure: ""
          port: 25
          authtype: LOGIN
      extraEnv:
        - name: VIRTUAL_HOST
          value: "cloud.${SECRET_DOMAIN}"
        - name: PHP_MEMORY_LIMIT
          value: 512M
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array('192.168.1.40')
          );
        protocol.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https'
          );
        phone_region.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'US'
          );

    internalDatabase:
      enabled: false

    cronjob:
      enabled: true

    redis:
      enabled: false

    mariadb:
      enabled: true
      architecture: standalone

      image:
        debug: true

      auth:
        username: nextcloud
        # password: set by valuesFrom
        # rootPassword: set by valuesFrom
        database: nextcloud

      primary:
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 5Gi

      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 1024Mi
