apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.13.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: core
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: nextcloud-secrets
      valuesKey: NEXTCLOUD_MARIADB_PASSWORD
      targetPath: mariadb.auth.password
      optional: false
  values:
    image:
      repository: nextcloud
      tag: "23.0.3"

    replicaCount: 1

    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 500Gi

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud-upload"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: apps-nextcloud-dav-redirect@kubernetescrd,apps-nextcloud-hsts-header@kubernetescrd
      hosts:
        - host: "cloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "cloud.${SECRET_DOMAIN}"
          secretName: "nextcloud-tls"

    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: NEXTCLOUD_ADMIN_USER
        passwordKey: NEXTCLOUD_ADMIN_PASSWORD
      extraEnv:
      - name: VIRTUAL_HOST
        value: cloud.windsor.family
      - name: OVERWRITEPROTOCOL
        value: https 
      - name: PHP_MEMORY_LIMIT
        value: 512M  

    internalDatabase:
      enabled: false

    cronjob:
      enabled: true

    redis:
      enabled: true

      master:
        storageClass: longhorn
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi

      replica:
        replicaCount: 0

    mariadb:
      enabled: true
      architecture: standalone

      auth:
        username: nextcloud
        # password: set by valuesFrom
        database: nextcloud

      primary:
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 5Gi

      resources:
        requests:
          memory: 256Mi
        limits:
          memory: 1024Mi
