apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: apps
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:5nCsa00=,iv:3GgFHOwqehWAPjeEJZZtDH0xEjN1C0OnecEwdZgaT2c=,tag:vUL3w+a7EV9pXFu05ZGdtw==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:HgJ04fTlFmLaRydDtb+wJtHuKNQyHuxdtFFTXqIkk7r7L2qHMw==,iv:2NRCPcG6dyhB5Q4jkagWeUq7XEW2aK4o3/30ZFumelg=,tag:alUyZqoDxm0Cg++cdgZTlA==,type:str]
    NEXTCLOUD_MARIADB_PASSWORD: ENC[AES256_GCM,data:bsPKKAnQa/hqh/itcjriiFFQni1XYb6kv3QsySJuyVUrtHrd2w==,iv:/r9rMVgMAPOIpAJT/9JZHHhDDpTA/P6PjmbvELWwm6E=,tag:vVrPdP/sCqVJF00UgMWtDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-03T05:00:12Z"
    mac: ENC[AES256_GCM,data:ZucLHSwRhlivZHWklXrDdT3lwWLo1BAcIH1FyRlCMy7LFwX82Y0EDpgxpFKDvbzKIqz1KZ/9gsOO5bs+J50NgM63dn77zM1zjFD/S4GIzk6aUZnI77LIjan+OhRecltBddVUZOT+FEWRCp2tqir2LR/Ya6HXsHpa00qE1OTOt+Q=,iv:jRFCldWqDSdsK5GB39As2+/zwORHyV+PRV3LL1Gn1ZE=,tag:nXqkO/1Qkxms5b3ZamH/GQ==,type:str]
    pgp:
        - created_at: "2022-04-03T05:00:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZjJPZjo0YzAQ/9HUCmtPAasXjMxt+chP6fp3w3hmxqGVaZnPO8xxIXDaJH
            Urv/v5g6yURJfROV/CuY81x9JulXIlB4XATQixmLbNj6ei7wjdn96OnAI7wSJ58t
            GnGqtrBLZa5Ux4QCnoEpcXrdOHJoLGh9sJi8pX+3LOt15KpJvomdtowkul3v1XIg
            1o7pHiWwwjp8pCuFxKfMLuZ2PKq0aco7FQS8qPpd7ipzVr+BCQgPP1tUqcZd/CfC
            VmjxFlGZtt2tUmso5ciCMFfHZV07VaS/qcjpQDrR/m3/y28qZX8ByCIn11jqwK6j
            0x622BN12KSfkb96Q5cle97LmpdaHrMx4JTX06k0x/2AU1tsY8NPo/M9IIyHRWhP
            Fe6leOsJIjG5AwFJycyIvi5N1DfwAftiSZuLqIGNod6osMKpx2ENzmakntzM/i1b
            8taskjdCtUX0r5fSnjyPfjZNytP+y5porC7Cy8cohWCV84dp23i8KxNiHmCk82oz
            9hJV8WSGxK4G6QhPUFTZUNzQJmPM0hz178Mn0xU57l0Eq38IVFLy0yfaQ26swhaQ
            MCC4aPwcFFp2gSFZD3rv6rVCrZD8WQD5nKb9Q+V0EVfRUut52ojFR+936fVJhlb4
            Se6LSdDmUfWIFkmMMpIwIfU+1vKDxDDd4d4Z8E763C7XQTDMVPFRzg0hfc2Xaj/S
            XAH2rrvGO1voPSun5j99PE4dYe2XfgcXjudNRJzaaUVSnYOBlRlpq+XDSPTkR/Gw
            pFmCbjIdJ4k/+L2D3KRsSN52Sxq+skrWTEi07eKr90Ew/Q7iv+JMJvJtKvLe
            =srC/
            -----END PGP MESSAGE-----
          fp: E1C112091AA75C8B2466F5F9B2DEF5BB0A09DD53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
