apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: apps
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:qCm6MpA=,iv:V6dNy9RBxQb0i3nD4lQXy/zhEIbzHmLNB0JXz6lm+O4=,tag:Wi5ctceZ1RFejADasFX6jQ==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:YvHYSCYkajdnlReOV6fe6/hShdElC88GfRDj7lEFwmMdjNch2w==,iv:PpmwPsMLzCH2gg4avEMXB8FpWyfK2hJZ94F3k44Pt88=,tag:wW6Ae9NOyMgNJfLKHEHSoQ==,type:str]
    NEXTCLOUD_MARIADB_PASSWORD: ENC[AES256_GCM,data:+1kYn8HxcMPEtV3ACnJNTqLEyQivGzG8IlHjyH/dbkeyYvkYPQ==,iv:b9Z49gMPQb84nJqSqmFkAj//buCPqW7XnVZHYG6gDWo=,tag:Wdib4EVNNFnyPxc2fkjxhw==,type:str]
    PROTONMAIL_BRIDGE_USER: ENC[AES256_GCM,data:u669QX22GwFChNN4FdVxU492fKVW,iv:A6VXh3kjVcOIwGpVydCtt7G+Fow9WoFhLfrsD1YSmdY=,tag:15QQx5pioNKDL1k+Lm8/JQ==,type:str]
    PROTONMAIL_BRIDGE_PASSWORD: ENC[AES256_GCM,data:KfZr95SXuuzPvO1lwpe1qIlKGyu2DA==,iv:8B3Hn2BiMfdpPZUIME6CeNts7UhJIm9Ywgsk7yg5hXA=,tag:/TFPikMdciWMCxtMFTfLKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-10T15:34:53Z"
    mac: ENC[AES256_GCM,data:UCeqnfw2oZbm+UQgNxiSBiiifiV+NkD+jAaxrZXA5pKeyG1X2eijHrXJDICJPkEARpjg3Sn+oKzP5OnqOfb6hFO5bIy8ITGLgLeKV7xnnqh0WdBXSg7QfnqJhVKxlirbjbOddyA9OqugihWjtaxJH7QhxKDmPqzJDc/ilPL25hE=,iv:J/Bppk9nXx2bRKvlCDORQsSIvdxJA9M5Wq+fj0Tx6mU=,tag:NB6+JUC/MjCPYCmwcTdxhQ==,type:str]
    pgp:
        - created_at: "2022-04-10T15:34:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZjJPZjo0YzAQ//ZZyAvEyH/KQG6JejGypNZ8Gq/xedHiScgTxsY462zSVV
            1klX+0Sm+c6o1KUkiIPcyhDDdYPu4kJx8PWpLqQ7m9R367VkJNFdJxzUk+OQdwDN
            2hmKBWTFeN95HloCXFxEB0Uo6BZ+aru4nAZLrX2eZphDOgo32Tm7qpzfQjwvnHwD
            brY1dpbtGGa75gETBjL0Pi2XG3X9tqPIlqGzCISWW92sX3YAmsD9a+u1S4W9cQND
            JqeLLQS8rghx5pqYr9RRD4PzYSTg5c8c2CcV3zgtRyOdfWDwXO9r4mqm9jEPp41c
            O1/tep1kcOMpwkhCP0ESfFjdJBTD3CoGSqlvjryeH/0N8t0SreYaoz+KSWJnWL0E
            ge0F8mC5xIF1dtyFEXjOKhClKDx6hvGkRiHK42JeINzzcUwFaOH35h5ayjQDlLmT
            wY0IQuABCpBl2DXPW24xGD8+i7xV2TCwtAorVBDqzzYc62x5NUrU39w130qHGcrj
            jdYr5Ixe1ifJqKw9PyccaEmmc3mG9f9pk1MjS7SqTJbj2lw34BBLVb/tvhdE+Unn
            NboOIJU47gtDV9Dim9ERHIJJ6Dha6IxY9iT0oE4YdnRKcKtWQL7WJeKMzwIWRllW
            konOyDhoUbU9XGuj514Hnyj7FHzcrL2qG4+20QFpcc74lrsevTIfXPv/Mnb/5nTS
            XgFJ7uukeApkSec4w5VB/cHyvbgm1gHqu/REWgyIaGnNWmVxbS8kvRC28NjJuWh9
            VYiv17RgRLLWDUt/S6gV1+9pqzSp38UAmckdW/kB6HD995D8apDVgQUSdUjl6Zg=
            =ixBD
            -----END PGP MESSAGE-----
          fp: E1C112091AA75C8B2466F5F9B2DEF5BB0A09DD53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
