apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.7.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: core
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: false
