apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
        dns01:
          cloudDNS:
            project: "${SECRET_GCP_PROJECTID}"
            serviceAccountSecretRef:
              name: gcloud-dns-key
              key: key.json
