---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack-chartsgit 
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io/
  timeout: 3m

