apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mailu.github.io/helm-charts
      chart: mailu
      version: 0.3.3
      sourceRef:
        kind: HelmRepository
        name: mailu-charts
        namespace: core
      interval: 5m
  values:
    certmanager:
      issuerName: letsencrypt-prod
    domain: "${SECRET_DOMAIN}"
    hostnames:
      - "mail.${SECRET_DOMAIN}"
      - "smtp.${SECRET_DOMAIN}"
      - "imap.${SECRET_DOMAIN}"
    initialAccount:
      domain: "${SECRET_DOMAIN}"
      username: postmaster
      password: "${SECRET_MAILU_POSTMASTER_PASSWORD}"
    secretKey: abc123
    # subnet: "${CLUSTER_CIDR}"
    logLevel: INFO
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns.alpha.kubernetes.io/target: "windsorfamily.mynetgear.com"
      hosts:
        - "mail.${SECRET_DOMAIN}"
      tls:
        hosts:
          - "mail.${SECRET_DOMAIN}"
    persistence:
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 50Gi
    rspamd:
      resources:
        limits:
          memory: 500Mi
    roundcube:
      resources:
        requests:
          cpu: 200m
        limits:
          cpu: 400m
