apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: core
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.38.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: core
      interval: 5m
  values:
    provider: google
    google:
      project: windsorfamily
      serviceAccountSecret: gcloud-dns-key
      serviceAccountSecretKey: key.json
    policy: sync
    registry: txt
    txtOwnerId: benny-cluster
    txtPrefix: "k8s."
    rbac:
      create: true
    domainFilters:
      - windsor.family
    sources:
      - ingress
