apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - traefik.yaml
  - hajimari.yaml
  - k8s-at-home.yaml
  - longhorn.yaml
  - nextcloud.yaml
  - kubernetes-dashboard.yaml