apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: core
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.6.2
    env:
      TZ: "America/Los_Angeles"

    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: home-assistant-sharedip
        ports:
          http:
            port: 8123
          homekittcp:
            enabled: true
            port: 21063
            targetPort: 21063
      otherudp:
        enabled: true
        primary: false
        name: home-assistant-udp
        annotations:
          metallb.universe.tf/allow-shared-ip: home-assistant-sharedip
        type: LoadBalancer
        ports:
          homekitudp:
            enabled: true
            port: 5353
            targetPort: 5353
            protocol: UDP

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/target: "windsorfamily.mynetgear.com"
        hosts:
          - host: "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "home.${SECRET_DOMAIN}"
            secretName: "home-assistant-tls"
