apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AeEPZ+cR+hZFcL+m5pw=,iv:PYZJK3oGu9oLJsv5jmDh260FVofQ1YkWBsHopHGb78s=,tag:ko7DeIVOgYbWtsFIX8U9aw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:711XRlHBc9vlqWcM/su5WiGMhFS3,iv:aXabfvIgwNJuSGVPBNb7vXBWnZW9akbX0h+F7hrV0Pw=,tag:XbS2BuwTW33TowRTS0xTeA==,type:str]
    SECRET_GCP_PROJECTID: ENC[AES256_GCM,data:frNFqr1Ujc9MnyO5/Q==,iv:j2wuCj2KnAfQafsREUzZGjl9pm0xIseLVN64df7dw28=,tag:kEIsUP2q1JNn452cyL8rOA==,type:str]
    SECRET_MAILU_POSTMASTER_PASSWORD: ENC[AES256_GCM,data:BuFUkguoI5sUQhCNe3J9yUpUEEFkd9Mr9bQf7w==,iv:z+TAHVfkMDTQU4Ibbwwl3Zk6zI77cG9OAVCeDN8fNV4=,tag:QRIoe7Bqfw4TR5e0/X1C8w==,type:str]
    SECRET_MAILU_SECRET_KEY: ENC[AES256_GCM,data:GKPJlwJsvzh/mP9RpNdKm1wbsiQg1XIqITx20w==,iv:Xz7GQukPPM1BvyBUuK3Cf0PeoTzABI0uwkadauA7nJw=,tag:D6PgllgllHkn6WSYpi+teQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-19T23:58:09Z"
    mac: ENC[AES256_GCM,data:s8Kyg35UF0C9ScGJQTpF59X7OxeOw9+IEkPs9gPQTIfnWkzYvP12rUWP0grif70oT6eWS7OlbSU+xJDD+jyQYmQt56qUsx7XxPjWYRMiTbPGPeKf4W9Ha2w2NZtGpomEfiIDtAVshoIBMl2y/2X3NzdDjEuQzc9dFALGHawcXV0=,iv:ZL5MlWyCBbp+ER0/9zpviHzn4EXsZpWOs2PlFOHhhEs=,tag:Be33fbus27G4ja8D+YYNwA==,type:str]
    pgp:
        - created_at: "2022-12-19T23:58:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZjJPZjo0YzAQ/+OQzgVlTpXDuvXb1/3o5AJvmHUjm26tw2Tv3F+IapNawJ
            0UfvLsdmeyOJOPOBaGGhK4L5Ewsynn+zwbQvN3H1gyBDdobqnHpNoTCDAMYFuE5E
            kZChkn3ndAX1rrVGeaoEPWxaqvJiTMewtmmjZc0FdEYy3/dQ8Zf8KdbJvkQvK+EX
            FR6fLZWMAPgFgaQ5CIjufY8OsGZECTXyUskrI76OwX6iAxGVqaknlqhLjWWRmpnD
            JantPnBv7wYL1BaME4vintXdJG2SciBRjGceVDaxCPEVqTSD/3tOoPHfB65Sky5a
            foIe9wtl5//gun+PSkQcOaOU2zssSxJ2OUOXoGPfyp5ovcI5XhkTM3J527bK0xVg
            AwuOtH96g/ABVnlfLcS66CxD9ACn8O0S832mLa/UITYk+gR7MqiULpjuWCL5LMtW
            YdVZz7GZNfW8fZyiiXdFOCoRdYKijIXX3v5QZIDCCEvDVcfQxmWC8uisZJ8IlEjh
            QX0LR1wNC33LalJ7/rCswFwGnTenvJqTBxQgVESd7ZGXQbOUcd5bCruy9a4Jy+w9
            MYALkdTFYfIgKykm0N3e7LD2JUbCH2W1TbWiuCJnlv4Ikma62ZJJV7eB9sLntLyk
            ZXo7UfY4B47ouEN3LIZ3ekxq0+rJRWZzZRvUvWtJ6P4VGrQw4iBuqXBmoJXUvQXS
            XgFumBEOe0I5ECydFK3U4BPWWtenZxRkFuswB0yfvp4P0UNiW/BcYak++1rCV4TX
            FUTv2yr83A6mpB75vqCkOvi9uJMRgCAlpzQ69ll8IJrjt9ROfctPt6rDTzX3Svo=
            =uvuw
            -----END PGP MESSAGE-----
          fp: E1C112091AA75C8B2466F5F9B2DEF5BB0A09DD53
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
